from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from core.domain.models import InventoryItem


class InventoryRepo(Protocol):
    def create_supplier_if_missing(self, name: str) -> int: ...
    def add_item(self, item: InventoryItem) -> int: ...
    def get_by_id(self, item_id: int) -> Optional[Dict[str, Any]]: ...
    def update_quantity(self, item_id: int, new_quantity: int, *, source: str, correlation_id: str) -> None: ...


class OrdersRepo(Protocol):
    def upsert_order_snapshot(self, store_id: int, order: Dict[str, Any]) -> int: ...
    def get_order_by_woo_id(self, store_id: int, woo_order_id: int) -> Optional[Dict[str, Any]]: ...
    def insert_order_line_item(
        self,
        *,
        order_id: int,
        woo_line_item_id: Optional[int],
        internal_product_id: Optional[int],
        sku: Optional[str],
        quantity: int,
        price: float,
    ) -> bool: ...
    def mark_inventory_applied(self, order_id: int) -> None: ...
    def mark_needs_review(self, order_id: int, needs_review: bool) -> None: ...
    def find_mapping(self, store_id: int, *, internal_id: Optional[int] = None, sku: Optional[str] = None, variation_id: Optional[int] = None, woo_product_id: Optional[int] = None) -> Optional[Dict[str, Any]]: ...


class SalesRepo(Protocol):
    def record_sale(self, item: Dict[str, Any], price: float, payment_method: str) -> Dict[str, Any]: ...


class SettingsProvider(Protocol):
    def get_store(self, store_id: int) -> Optional[Dict[str, Any]]: ...
    def get_default_store(self) -> Optional[Dict[str, Any]]: ...
    def get_store_settings(self, store_id: int) -> Dict[str, Any]: ...


class Clock(Protocol):
    def now_iso(self) -> str: ...
